# Generated by Django 6.0.1 on 2026-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view_inbox', 'Can view inbox'), ('can_mark_as_read', 'Can mark messages as read'), ('can_archive_message', 'Can archive messages'), ('can_view_dashboard', 'can view dashboard')],
            },
        ),
    ]
