# Generated by Django 6.0 on 2026-01-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'permissions': [('can_view_inbox', 'Can view inbox'), ('can_mark_as_read', 'Can mark messages as read'), ('can_delete_messages', 'Can delete messages')]},
        ),
    ]
