# Generated by Django 6.0 on 2026-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'permissions': [('can_view_inbox', 'Can view inbox'), ('can_mark_as_read', 'Can mark messages as read'), ('can_archive_message', 'Can archive messages')]},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
