# Generated by Django 6.0 on 2026-01-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'permissions': [('can_view_inbox', 'Can view inbox'), ('can_mark_as_read', 'Can mark messages as read'), ('can_archive_message', 'Can archive messages'), ('can_view_dashboard', 'can view dashboard')]},
        ),
    ]
